### ISSUE TITLE
加载vae模型时报错

### ISSUE THREAD

**Issue by jasonlbx13** [alibaba/animate-anything#4]
您好，在推理时发生以下错误，请问是否为vae模型不匹配导致的呢？谢谢
Traceback (most recent call last):
  File "/home/data/liboxian/animate-anything/train.py", line 1167, in <module>
    main_eval(**args_dict)
  File "/home/data/liboxian/animate-anything/train.py", line 1134, in main_eval
    noise_scheduler, tokenizer, text_encoder, vae, unet = load_primary_models(pretrained_model_path, motion_mask, motion_strength)
  File "/home/data/liboxian/animate-anything/train.py", line 134, in load_primary_models
    vae = AutoencoderKL.from_pretrained(pretrained_model_path, subfolder="vae")
  File "/home/liboxian/miniconda3/envs/sd/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 583, in from_pretrained
    raise ValueError(
ValueError: Cannot load <class 'diffusers.models.autoencoder_kl.AutoencoderKL'> from output/latent/animate_anything_512_v1.01 because the following keys are missing: 
 decoder.mid_block.attentions.0.proj_attn.bias, decoder.mid_block.attentions.0.proj_attn.weight, encoder.mid_block.attentions.0.query.weight, encoder.mid_block.attentions.0.query.bias, decoder.mid_block.attentions.0.key.bias, decoder.mid_block.attentions.0.query.weight, decoder.mid_block.attentions.0.key.weight, decoder.mid_block.attentions.0.value.weight, encoder.mid_block.attentions.0.key.bias, encoder.mid_block.attentions.0.proj_attn.bias, decoder.mid_block.attentions.0.query.bias, decoder.mid_block.attentions.0.value.bias, encoder.mid_block.attentions.0.value.weight, encoder.mid_block.attentions.0.key.weight, encoder.mid_block.attentions.0.proj_attn.weight, encoder.mid_block.attentions.0.value.bias.

**Comment by jasonlbx13** [comment]
更换pytorch==2.0.1为pytorch==2.0.0解决了这个问题
