### ISSUE TITLE
Interference issue

### ISSUE THREAD

**Issue by liw8hz** [alibaba/animate-anything#46]
running CLI python train.py --config ./animate_anything_512_v1.02/config.yaml --eval validation_data.prompt_image=example/barbie2.jpg validation_data.prompt='A cartoon girl is talking.'

Traceback (most recent call last):
  File "train.py", line 1134, in <module>
    main_eval(**args_dict)
  File "train.py", line 1121, in main_eval
    batch_eval(unet, text_encoder, vae, vae_processor, lora_manager, pretrained_model_path, 
  File "train.py", line 1081, in batch_eval
    precision = eval(pipeline, vae_processor, 
  File "train.py", line 1020, in eval
    video_frames, video_latents = pipeline(
  File "/home/kka/.local/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/kka/AI/animate-anything/models/pipeline.py", line 205, in __call__
    video = tensor2vid(video_tensor)
TypeError: tensor2vid() missing 1 required positional argument: 'processor'

looks like to miss an argument which I don't find it at pipeline.py, it's wrong coding or something else?

**Comment by daizuozhuo** [comment]
It seems your diffusers version is not correct. This code is tested with diffusers==0.24.0
