### ISSUE TITLE
How to setup dataset

### ISSUE THREAD

**Issue by SwayStar123** [alibaba/animate-anything#49]
I cannot figure out how to setup my training data and how to adjust train_svd.yaml. As captions are not needed for SVD i only have a dataset with videos. 

videos
   |----- video1.mp4
   |----- video2.mp4

Like this i have a videos folder, but setting `video_dir`to "/videos" and "json_path" to "blip_generated.json" does not work. I get this error

```
Traceback (most recent call last):
  File "D:\MyStuff\Programming\Python\AI\animate-anything\utils\dataset.py", line 182, in load_from_json
    with open(path) as jpath:
         ^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'blip_generated.json'
Non-existant JSON path. Skipping.
Traceback (most recent call last):
  File "D:\MyStuff\Programming\Python\AI\animate-anything\train_svd.py", line 841, in <module>
    main(**args_dict)
  File "D:\MyStuff\Programming\Python\AI\animate-anything\train_svd.py", line 585, in main
    train_dataloader = torch.utils.data.DataLoader(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\MyStuff\Programming\Python\AI\animate-anything\animate_anything\Lib\site-packages\torch\utils\data\dataloader.py", line 351, in __init__
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore[arg-type]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\MyStuff\Programming\Python\AI\animate-anything\animate_anything\Lib\site-packages\torch\utils\data\sampler.py", line 107, in __init__
    raise ValueError("num_samples should be a positive integer "
ValueError: num_samples should be a positive integer value, but got num_samples=0
```

**Comment by daizuozhuo** [comment]
Currently the training requires captions. You can generate captions following instructions in readme.
