### ISSUE TITLE
OSError: Error no file named config.json found in directory output/latent/animate_anything_512_v1.02.

### ISSUE THREAD

**Issue by ozgurshn** [alibaba/animate-anything#69]
Could you help me with this error please?
I followed the Colab commands 
When I run the command below, I get this error. 
!python train.py --config output/latent/animate_anything_512_v1.02/config.yaml --eval validation_data.prompt_image=example/barbie2.jpg validation_data.prompt='A cartoon girl is talking.'

Traceback (most recent call last):
  File "/content/animate-anything/train.py", line 869, in <module>
    main_eval(**args_dict)
  File "/content/animate-anything/train.py", line 838, in main_eval
    noise_scheduler, tokenizer, text_encoder, vae, unet = load_primary_models(pretrained_model_path, motion_strength=motion_strength)
  File "/content/animate-anything/train.py", line 89, in load_primary_models
    vae = AutoencoderKL.from_pretrained(pretrained_model_path, subfolder="vae")
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/modeling_utils.py", line 712, in from_pretrained
    config, unused_kwargs, commit_hash = cls.load_config(
  File "/usr/local/lib/python3.10/dist-packages/diffusers/configuration_utils.py", line 365, in load_config
    raise EnvironmentError(
OSError: Error no file named config.json found in directory output/latent/animate_anything_512_v1.02.

**Comment by ozgurshn** [comment]
that's my mistake. tar operation is interrupted.
