### ISSUE TITLE
cannot import name 'cached_download'

### ISSUE THREAD

**Issue by UESENPAI** [alibaba/animate-anything#83]
Greeting

I have followed your installation instruction and got the following errors

(animation) C:\Users\Doctor\Downloads\animate-anything-main>python train.py --config output/latent/{download_model}/config.yaml --eval validation_data.prompt_image=example/barbie2.jpg validation_data.prompt='A cartoon girl is talking.'
Traceback (most recent call last):
  File "C:\Users\Doctor\Downloads\animate-anything-main\train.py", line 20, in <module>
    import diffusers
  File "C:\ProgramData\anaconda3\envs\animation\lib\site-packages\diffusers\__init__.py", line 5, in <module>
    from .utils import (
  File "C:\ProgramData\anaconda3\envs\animation\lib\site-packages\diffusers\utils\__init__.py", line 38, in <module>
    from .dynamic_modules_utils import get_class_from_dynamic_module
  File "C:\ProgramData\anaconda3\envs\animation\lib\site-packages\diffusers\utils\dynamic_modules_utils.py", line 28, in <module>
    from huggingface_hub import HfFolder, cached_download, hf_hub_download, model_info
ImportError: cannot import name 'cached_download' from 'huggingface_hub' (C:\ProgramData\anaconda3\envs\animation\lib\site-packages\huggingface_hub\__init__.py)

I have reinstalled all prerequiste files and tried again but not worked

(Coursely, I have downloaded the model and change its root folder name to {download_model} and placed into output/latent)

I have upgraded all modules but not worked. Anybody who have experienced same things?

**Comment by UESENPAI** [comment]
...\Anaconda\envs\animation\Lib\site-packages\diffusers\utils

I have changed dynamic_modules_utils.py file and tried
`
from huggingface_hub import HfFolder, hf_hub_download, model_info
`

to

`
from huggingface_hub import HfFolder, hf_hub_download, model_info
`

and

`
resolved_module_file = cached_download(
    github_url,
    cache_dir=cache_dir,
    force_download=force_download,
    proxies=proxies,
    resume_download=resume_download,
    local_files_only=local_files_only,
    use_auth_token=False,
)
`

to


`
resolved_module_file = hf_hub_download(
    repo_id=pretrained_model_name_or_path,
    filename=module_file,
    cache_dir=cache_dir,
    force_download=force_download,
    proxies=proxies,
    resume_download=resume_download,
    local_files_only=local_files_only,
    token=use_auth_token,
)
`

and got below error

`
E:\animate-anything>python train.py --config output/latent/{download_model}/config.yaml --eval validation_data.prompt_image=example/barbie2.jpg validation_data.prompt='A cartoon girl is talking.'
The cache for model files in Transformers v4.22.0 has been updated. Migrating your old cache. This is a one-time only operation. You can interrupt this and resume the migration later on by calling `transformers.utils.move_cache()`.
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "E:\animate-anything\train.py", line 866, in <module>
    cli_dict = OmegaConf.from_dotlist(args.rest)
  File "E:\Anaconda\envs\animation\lib\site-packages\omegaconf\omegaconf.py", line 247, in from_dotlist
    conf.merge_with_dotlist(dotlist)
  File "E:\Anaconda\envs\animation\lib\site-packages\omegaconf\basecontainer.py", line 209, in merge_with_dotlist
    value = yaml.load(value, Loader=get_yaml_loader())
  File "C:\Users\Doctor\AppData\Roaming\Python\Python310\site-packages\yaml\__init__.py", line 81, in load
    return loader.get_single_data()
  File "C:\Users\Doctor\AppData\Roaming\Python\Python310\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "C:\Users\Doctor\AppData\Roaming\Python\Python310\site-packages\yaml\composer.py", line 35, in get_single_node
    if not self.check_event(StreamEndEvent):
  File "C:\Users\Doctor\AppData\Roaming\Python\Python310\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
  File "C:\Users\Doctor\AppData\Roaming\Python\Python310\site-packages\yaml\parser.py", line 142, in parse_implicit_document_start
    if not self.check_token(DirectiveToken, DocumentStartToken,
  File "C:\Users\Doctor\AppData\Roaming\Python\Python310\site-packages\yaml\scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "C:\Users\Doctor\AppData\Roaming\Python\Python310\site-packages\yaml\scanner.py", line 247, in fetch_more_tokens
    return self.fetch_single()
  File "C:\Users\Doctor\AppData\Roaming\Python\Python310\site-packages\yaml\scanner.py", line 652, in fetch_single
    self.fetch_flow_scalar(style='\'')
  File "C:\Users\Doctor\AppData\Roaming\Python\Python310\site-packages\yaml\scanner.py", line 666, in fetch_flow_scalar
    self.tokens.append(self.scan_flow_scalar(style))
  File "C:\Users\Doctor\AppData\Roaming\Python\Python310\site-packages\yaml\scanner.py", line 1151, in scan_flow_scalar
    chunks.extend(self.scan_flow_scalar_spaces(double, start_mark))
  File "C:\Users\Doctor\AppData\Roaming\Python\Python310\site-packages\yaml\scanner.py", line 1238, in scan_flow_scalar_spaces
    raise ScannerError("while scanning a quoted scalar", start_mark,
yaml.scanner.ScannerError: while scanning a quoted scalar
  in "<unicode string>", line 1, column 1:
    'A
    ^
found unexpected end of stream
  in "<unicode string>", line 1, column 3:
    'A
`

**Comment by UESENPAI** [comment]
Did a stupid mistake. Do not change the folder name. folder name is hard-coded.
