### ISSUE TITLE
cannot import name 'cached_download' from 'huggingface_hub'

### ISSUE THREAD

**Issue by MohammadAsif-SDE** [alibaba/animate-anything#84]
Despite Installing all the packages as instructed i still occurs the same issue
"cannot import name 'cached_download' from 'huggingface_hub'"

#I have Tried Multiple times installing in a different environment as well but this issue doesn't getting cleared.
#I Even Cross verified the package installation of the HuggingFace_Hub and tried installing the official library as well but it still gets the error.
#I don't know since i was into setting up the project from past 2 days and it still doesn't get cleared and i keeps getting this error.
#I tried Multiple ways but every-time i uses different approach i keeps getting the version confliction with pytorch and the diffusive library but i fixed those but, I cant able to fix the below issue. Do please suggest the Fix...........................

C:\projects\animate-anything>python train.py --config output/latent/animate_anything_512_v1.02.tar/config.yaml --eval validation_data.prompt_image=example/qingming2.jpg validation_data.prompt='Peoples are walking on the street.' validation_data.mask=example/qingming2_label.jpg
Traceback (most recent call last):
  File "C:\projects\animate-anything\train.py", line 20, in <module>
    import diffusers
  File "C:\Python39\lib\site-packages\diffusers\__init__.py", line 5, in <module>
    from .utils import (
  File "C:\Python39\lib\site-packages\diffusers\utils\__init__.py", line 38, in <module>
    from .dynamic_modules_utils import get_class_from_dynamic_module
  File "C:\Python39\lib\site-packages\diffusers\utils\dynamic_modules_utils.py", line 28, in <module>
    from huggingface_hub import HfFolder, cached_download, hf_hub_download, model_info
ImportError: cannot import name 'cached_download' from 'huggingface_hub' (C:\Python39\lib\site-packages\huggingface_hub\__init__.py)

Plz Help me out to make a setup.....
![Screenshot-animate-anything ](https://github.com/user-attachments/assets/014610b6-d736-40b5-9c29-c9fd4b8abd35)

**Comment by MohammadAsif-SDE** [comment]
@daizuozhuo @eltociear @Leojc @sculmh anybody please help na.

**Comment by Leojc** [comment]
try downgrade it: ```pip install huggingface_hub==0.25.2```
